version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-26-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "library/build.gradle" }}
      - run:
          name: Debug
          command: echo $ANDROID_HOME && which sdkmanager && which avdmanager && sdkmanager --list --verbose
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "library/build.gradle" }}
      - run:
          name: Run Tests
          command: ./gradlew check
      - store_artifacts:
          path: library/build/reports
          destination: reports
      - store_test_results:
          path: library/build/test-results
